CROP_CONFIG = {
    "Tomato": {
        "base_yield": 3000,
        "min_temperature": 18,
        "max_temperature": 32,
        "water_requirement": 6,
        "growth_duration": 90,
        "disease_sensitivity": 0.8,
        "drought_sensitivity": 0.7,
        "heat_sensitivity": 0.7,
    },

    "Rice": {
        "base_yield": 2500,
        "min_temperature": 20,
        "max_temperature": 35,
        "water_requirement": 8,
        "growth_duration": 120,
        "disease_sensitivity": 0.7,
        "drought_sensitivity": 0.8,
        "heat_sensitivity": 0.6,
    },

    "Wheat": {
        "base_yield": 2200,
        "min_temperature": 10,
        "max_temperature": 30,
        "water_requirement": 5,
        "growth_duration": 120,
        "disease_sensitivity": 0.6,
        "drought_sensitivity": 0.6,
        "heat_sensitivity": 0.8,
    },

    "Maize": {
        "base_yield": 2800,
        "min_temperature": 18,
        "max_temperature": 32,
        "water_requirement": 6,
        "growth_duration": 100,
        "disease_sensitivity": 0.5,
        "drought_sensitivity": 0.7,
        "heat_sensitivity": 0.7,
    },

    "Sorghum": {
        "base_yield": 1800,
        "min_temperature": 18,
        "max_temperature": 35,
        "water_requirement": 4,
        "growth_duration": 110,
        "disease_sensitivity": 0.4,
        "drought_sensitivity": 0.4,
        "heat_sensitivity": 0.5,
    },

    "Pearl Millet": {
        "base_yield": 1600,
        "min_temperature": 20,
        "max_temperature": 38,
        "water_requirement": 3,
        "growth_duration": 90,
        "disease_sensitivity": 0.4,
        "drought_sensitivity": 0.3,
        "heat_sensitivity": 0.4,
    },

    "Chickpea": {
        "base_yield": 1400,
        "min_temperature": 15,
        "max_temperature": 30,
        "water_requirement": 3,
        "growth_duration": 100,
        "disease_sensitivity": 0.5,
        "drought_sensitivity": 0.6,
        "heat_sensitivity": 0.6,
    },

    "Pigeon Pea": {
        "base_yield": 1300,
        "min_temperature": 20,
        "max_temperature": 35,
        "water_requirement": 4,
        "growth_duration": 150,
        "disease_sensitivity": 0.5,
        "drought_sensitivity": 0.5,
        "heat_sensitivity": 0.5,
    },

    "Green Gram": {
        "base_yield": 1000,
        "min_temperature": 20,
        "max_temperature": 35,
        "water_requirement": 3,
        "growth_duration": 70,
        "disease_sensitivity": 0.6,
        "drought_sensitivity": 0.6,
        "heat_sensitivity": 0.6,
    },

    "Soybean": {
        "base_yield": 1800,
        "min_temperature": 18,
        "max_temperature": 32,
        "water_requirement": 5,
        "growth_duration": 110,
        "disease_sensitivity": 0.6,
        "drought_sensitivity": 0.6,
        "heat_sensitivity": 0.6,
    },

    "Groundnut": {
        "base_yield": 1700,
        "min_temperature": 20,
        "max_temperature": 32,
        "water_requirement": 4,
        "growth_duration": 120,
        "disease_sensitivity": 0.5,
        "drought_sensitivity": 0.5,
        "heat_sensitivity": 0.6,
    },

    "Mustard": {
        "base_yield": 1200,
        "min_temperature": 10,
        "max_temperature": 28,
        "water_requirement": 3,
        "growth_duration": 110,
        "disease_sensitivity": 0.5,
        "drought_sensitivity": 0.5,
        "heat_sensitivity": 0.7,
    },

    "Cotton": {
        "base_yield": 2000,
        "min_temperature": 20,
        "max_temperature": 35,
        "water_requirement": 5,
        "growth_duration": 160,
        "disease_sensitivity": 0.6,
        "drought_sensitivity": 0.6,
        "heat_sensitivity": 0.6,
    },

    "Sugarcane": {
        "base_yield": 7000,
        "min_temperature": 20,
        "max_temperature": 38,
        "water_requirement": 8,
        "growth_duration": 300,
        "disease_sensitivity": 0.5,
        "drought_sensitivity": 0.8,
        "heat_sensitivity": 0.5,
    },

    "Potato": {
        "base_yield": 2200,
        "min_temperature": 10,
        "max_temperature": 25,
        "water_requirement": 4,
        "growth_duration": 100,
        "disease_sensitivity": 0.7,
        "drought_sensitivity": 0.6,
        "heat_sensitivity": 0.8,
    },
}